import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

const Home: NextPage = () => {
  return (
    <div className="font-sans flex min-h-screen flex-col md:flex-row">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="border w-full h-full p-4">
        <h1 className="text-xl">Hello</h1>
      </div>
    </div>
  );
};

export default Home;
